version: '3'
services:
  mongo:
    image: mongo:bionic
    networks:
      - mikarezoo-flashcards_network
    container_name: "mikarezoo-flashcards_mongo_docker"
    env_file:
     - ./mongo/.env
    volumes:
      - "./mongo/volume:/data/db"
      - "./mongo/dumps:/dumps"
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - "./mongo/.dbshell:/home/mongodb/.dbshell"
  redis:
    image: redis:latest
    networks:
      - mikarezoo-flashcards_network
  app:
    depends_on: [mongo]
    image: mikarezoo-flashcards-flask
    container_name: "mikarezoo-flashcards_app"
    networks:
      - mikarezoo-flashcards_network
    build:
      context: "./backend"
    env_file:
      - ./mongo/.env
      - ./backend/.env
    volumes:
      - "./logs/:/app/logs/"
      - "./backend:/app/backend/"
      - "./frontend/dist:/app/backend/templates:ro"
      - "./frontend/dist/static:/app/backend/static:ro"
    command: "python -m backend"


networks:
  mikarezoo-flashcards_network:
    driver: bridge
