version: '3'
services:
  vuecli:
    image: "mikarezoo-flashcards-vue2"
    networks:
      - "mikarezoo-flashcards_network"
    build:
      context: "./frontend"
    volumes:
      - "./frontend:/home/node"
    ports:
      - "8064:8080"
    command: "npm run serve"

  
networks:
  mikarezoo-flashcards_network:
    driver: bridge
